services:
  web:
    # TODO: 使用 nginx image
    image:
    container_name: practice-nginx
    restart:
    ports:
      # TODO: host 8080 對應 container 80
      -
    volumes:
      # TODO: 將 ./html 掛載到 Nginx 靜態頁目錄，並設為唯讀
      -

  redis:
    # TODO: 使用 redis:7-alpine
    image:
    container_name: practice-redis
    restart:
    ports:
      # TODO: host 6379 對應 container 6379
      -
