services:
  web:
    image: nginx
    container_name: challenge-web
    restart: unless-stopped
    ports:
      - "8084:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro

  db:
    image: mysql:8.0
    container_name: challenge-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: challenge_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3308:3306"
    volumes:
      - challenge-db-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: challenge-redis
    restart: unless-stopped
    ports:
      - "6380:6379"

volumes:
  challenge-db-data:
